---
abstract: 'Because v0.09 uses HTTP::Tiny and is broken'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: '0.4004'
  Test::Requires: '0.06'
  version: '0.88'
configure_requires:
  Module::Build: '0.4004'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-Devel-Cover-Report-Coveralls-usingfurl
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - lib/Devel
provides:
  Alt::Devel::Cover::Report::Coveralls::usingfurl:
    file: lib/Alt/Devel/Cover/Report/Coveralls/usingfurl.pm
    version: v0.3.1
requires:
  Devel::Cover: '1.02'
  Furl: '0'
  IO::Socket::SSL: '0'
  JSON::PP: '0'
  YAML: '0'
  perl: '5.008005'
  version: '0.88'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alt-Devel-Cover-Report-Coveralls-usingfurl
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.3.1
